# Generated by Django 5.0.2 on 2024-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='null', max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
