# Generated by Django 5.1.1 on 2024-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=70)),
                ('color', models.CharField(blank=True, max_length=70)),
                ('price', models.CharField(max_length=10)),
                ('delivery', models.CharField(choices=[('PERSONAL DELIVERY = Extra 500', 'PERSONAL DELIVERY = Extra 500'), ('SELF', 'SELF')], default='SELF', max_length=50)),
            ],
        ),
    ]
