# Generated by Django 5.0.4 on 2024-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_remove_booking_date_booking_file_alter_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='file',
            new_name='aadhar',
        ),
        migrations.AddField(
            model_name='booking',
            name='driving_license',
            field=models.FileField(blank=True, upload_to='docs/'),
        ),
    ]
