# Generated by Django 5.0.4 on 2024-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_rename_file_booking_aadhar_booking_driving_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
